//! Key -> [`Action`] mapping. Vim keys and arrows both work.

use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    Cast,
    Quit,
    Help,
    Up,
    Down,
    PageUp,
    PageDown,
    Top,
    Bottom,
    FocusNext,
    Select,
    Back,
    TogglePause,
    Next,
    Prev,
    SeekBack,
    SeekForward,
    VolumeUp,
    VolumeDown,
    Sync,
    Search,
    FindOnline,
    CategoryPrev,
    CategoryNext,
    ToggleCards,
    Shuffle,
    Repeat,
    Autoplay,
    ToggleQueue,
    PlayNext,
    Radio,
    Like,
    Dislike,
    AddToPlaylist,
    Remove,
    MoveUp,
    MoveDown,
    ClearQueue,
    Download,
    SaveOrFollow,
    PlaylistMenu,
    Lyrics,
    Sleep,
    Home,
    History,
    Downloads,
    Albums,
    Artists,
    SignIn,
}

/// `(keys, description)` rows for the help popup.
pub const HELP: &[(&str, &str)] = &[
    ("↑/↓  k/j, PgUp/PgDn  g/G", "move · page · top / bottom"),
    ("Tab  h/l", "switch pane"),
    ("Enter / double-click", "open / play"),
    ("b  Backspace", "back"),
    ("1 2 3 4 5", "home · history · downloads · albums · artists"),
    ("Space   n / p", "play / pause · next / previous"),
    ("← / →  click bar", "seek"),
    ("+ / -", "volume"),
    ("/", "filter the list (Esc clears)"),
    ("o   [ ]", "search YouTube Music · other category"),
    ("i", "albums / artists on this page"),
    ("s / e / A", "shuffle / repeat / autoplay"),
    ("v", "queue (x remove, J/K move, X clear)"),
    ("u / R", "play next / start radio"),
    ("f / d", "like / dislike"),
    ("a / x", "add to / remove from playlist"),
    ("D", "download for offline"),
    ("S", "save album / follow artist"),
    ("m", "playlist menu (new, rename, delete)"),
    ("t", "lyrics"),
    ("z / C", "sleep timer / play on a Chromecast"),
    ("r / L", "sync library / sign in"),
    ("?   q", "this help · quit"),
];

pub fn action_for(key: KeyEvent) -> Option<Action> {
    if key.modifiers.contains(KeyModifiers::CONTROL) {
        return (key.code == KeyCode::Char('c')).then_some(Action::Quit);
    }
    Some(match key.code {
        KeyCode::Char('q') => Action::Quit,
        KeyCode::Char('?') => Action::Help,
        KeyCode::Up | KeyCode::Char('k') => Action::Up,
        KeyCode::Down | KeyCode::Char('j') => Action::Down,
        KeyCode::PageUp => Action::PageUp,
        KeyCode::PageDown => Action::PageDown,
        KeyCode::Home | KeyCode::Char('g') => Action::Top,
        KeyCode::End | KeyCode::Char('G') => Action::Bottom,
        KeyCode::Tab | KeyCode::BackTab | KeyCode::Char('h') | KeyCode::Char('l') => {
            Action::FocusNext
        }
        KeyCode::Enter => Action::Select,
        KeyCode::Backspace | KeyCode::Char('b') => Action::Back,
        KeyCode::Char(' ') => Action::TogglePause,
        KeyCode::Char('n') => Action::Next,
        KeyCode::Char('p') => Action::Prev,
        KeyCode::Left => Action::SeekBack,
        KeyCode::Right => Action::SeekForward,
        KeyCode::Char('+') | KeyCode::Char('=') => Action::VolumeUp,
        KeyCode::Char('-') => Action::VolumeDown,
        KeyCode::Char('r') => Action::Sync,
        KeyCode::Char('/') => Action::Search,
        KeyCode::Char('o') => Action::FindOnline,
        KeyCode::Char('[') => Action::CategoryPrev,
        KeyCode::Char(']') => Action::CategoryNext,
        KeyCode::Char('i') => Action::ToggleCards,
        KeyCode::Char('s') => Action::Shuffle,
        KeyCode::Char('e') => Action::Repeat,
        KeyCode::Char('A') => Action::Autoplay,
        KeyCode::Char('v') => Action::ToggleQueue,
        KeyCode::Char('u') => Action::PlayNext,
        KeyCode::Char('R') => Action::Radio,
        KeyCode::Char('f') => Action::Like,
        KeyCode::Char('d') => Action::Dislike,
        KeyCode::Char('a') => Action::AddToPlaylist,
        KeyCode::Char('x') | KeyCode::Delete => Action::Remove,
        KeyCode::Char('K') => Action::MoveUp,
        KeyCode::Char('J') => Action::MoveDown,
        KeyCode::Char('X') => Action::ClearQueue,
        KeyCode::Char('D') => Action::Download,
        KeyCode::Char('S') => Action::SaveOrFollow,
        KeyCode::Char('m') => Action::PlaylistMenu,
        KeyCode::Char('t') => Action::Lyrics,
        KeyCode::Char('z') => Action::Sleep,
        KeyCode::Char('C') => Action::Cast,
        KeyCode::Char('1') => Action::Home,
        KeyCode::Char('2') => Action::History,
        KeyCode::Char('3') => Action::Downloads,
        KeyCode::Char('4') => Action::Albums,
        KeyCode::Char('5') => Action::Artists,
        KeyCode::Char('L') => Action::SignIn,
        _ => return None,
    })
}
